### ISSUE TITLE
When scanning an EAN-13 bar code the last digit is missing

### ISSUE THREAD

**Issue by vksd13** [luis901101/honeywell_scanner#1]
When scanning an EAN-13 bar code the last digit is missing

**Comment by luis901101** [comment]
The last digit on EAN-13 bar codes is known as **the check digit**, this digit is not part of the code itself and by default is not included in the scanned code, anyway if you want to include **the check digit** in the scanned code result you need to set the corresponding property `DEC_EAN13_CHECK_DIGIT_TRANSMIT` to `true` in the scanner properties, something like this:

```dart
Map<String, dynamic> properties = {
  //here all your required properties like code formats...
};
properties['DEC_EAN13_CHECK_DIGIT_TRANSMIT'] = true;
honeywellScanner.setProperties(properties);
```

**Note:** there are lot of properties available to set to the scanner, that properties are part of the honeywell scanner sdk, I will update the README to indicate where to find this set of properties for devs to know what can be done with properties.

**Comment by khaledmurtaja** [comment]
hello all,

if anyone could help me to know which property, i need to set to true for reading the last digit of this linear code 

i tried all of these, but without solution
'DEC_EAN8_CHECK_DIGIT_TRANSMIT': true,
          'DEC_EAN8_ENABLED':true,
          'DEC_EAN8_2CHAR_ADDENDA_ENABLED':true,
          'DEC_EAN8_5CHAR_ADDENDA_ENABLED':true,
          'DEC_EAN8_ADDENDA_REQUIRED':true,
          'DEC_EAN8_ADDENDA_SEPARATOR':true

![Image](https://github.com/user-attachments/assets/745f12ef-2dda-4528-9c24-b73a85641eb0)
