### ISSUE TITLE
UPC-A code is not reading properly

### ISSUE THREAD

**Issue by go2hyder** [luis901101/honeywell_scanner#22]
The plugin not reading UPC-A code as the last digit is missing from the scanned result.

![barcode (1)](https://github.com/user-attachments/assets/6204d8fa-934d-4ed4-8477-5b13a3a123be)

The above image the barcode value is 725272730706. But the plugin reading it as 72527273070. The last digit 6 is missing.

In the device scan setting, the Send Check digit is already checked. But still having same issue

**Comment by go2hyder** [comment]
Fixed by adding `"DEC_UPCA_CHECK_DIGIT_TRANSMIT": true` in the properties

**Comment by luis901101** [comment]
Hi sorry for the late answer, exactly by setting the property you get the expected behavior, whatever extra conf you need to do should be done by specifying properties, here a similar issue with EAN: https://github.com/luis901101/honeywell_scanner/issues/1
