### ISSUE TITLE
Compiled example on IDX downloaded on a CT50  but application does not run

### ISSUE THREAD

**Issue by dandumit** [luis901101/honeywell_scanner#24]
Thank you for your work and example provided!

I have managed to compile example on idx.google.com 
I have made "flutter build apk" and loaded on my CT50 device, Android 6.0.1 , hw version MVT , aplication start but says Device Supported: False.
I can click on start / stop scanner but does not make something usefull.
Any hint would be highly apreciated ! 

Thank you,
Daniel

**Comment by dandumit** [comment]
Update. I have borrowed and installed build test aplication on a EDA71 device and works nice ! 
Please if you can provide any hint what to try on CT50 since this is my device .
Can I restrict somehow Android release  ? EDA71 it's on android 10 . CT50 it's on Android 6.0.1

Thank  you,
Daniel

**Comment by luis901101** [comment]
Hi, Android version should not be a problem. I have not tested any **Dolphin CT50** my self but if it is on the default supported devices it should work, that list is provided by Honeywell.
I recommend you two things:
1. Try using a different version of the Data Collection library `honeywell.aar` simply download a newer or older version from from Honeywell portal, check the readme.
2. Debug the Android project and check whatever log or exception when starting the data collection service so you can see the cause.

**Comment by dandumit** [comment]
Thank you Luis for guidance ! 

I did not found exactly honeywell.aar. I have found DataColection.aar inside honeywell-android-data-collection-sdk.zip
I have tried releases : 054 - and crashes totally
085, 096, 0143 and does not scan.

What seems to be strange it's that "honeywellScanner.isSupported();" reports that's not supported but device it's CT50.

I have upgraded this device to Android 6.0.1.  I see that there are 2 releases GMS and Non GMS. What would be preffered  ?

Another question : if I push side buttons for scanning on eda71 start scanner light even without sw started.  on CT50 nothing happens. 

What else to check  ?  BEsides debug ( I don't have yet a docking station for usb debug -  I will try over ethernet)

Should I reupdate device to a GMS one ?  Are those devices depending on a licence per device that has to be installed locally ?

Thank you,
Daniel

**Comment by luis901101** [comment]
Hi, yeah `DataColection.aar` is the original name of the .aar package in the Honeywell sdk, to use it you just need to rename it to `honeywell.aar` and copy it to your project.

If the `honeywellScanner.isSupported();` returns false that means that the creation of `AidcManager.create(context, this);` didn't complete successfully, you can check it here:
https://github.com/luis901101/honeywell_scanner/blob/baa059841a89d6fbe2cd83e0890fbf0bab1f3c3b/android/src/main/java/com/plugin/flutter/honeywell_scanner/HoneywellScannerNative.java#L48-L55

Honeywell PDA's are scanners so the physical buttons will trigger a scan event no matter if you pressed the "Start scanner" button in the example app... what the "Start scanner" does is to listen to the scanner events... however, if my memory serves me correctly you can also disable/enable physical button scanning by setting properties through the plugin or through the PDA's system settings. 

**Something important here**... If your CT50 does nothing when you press on the physical scan buttons then check the PDA's system settings so you are sure the scanner is enabled and active... the point here is to check the PDA works fine outside the plugin example so then you can check with the plugin... a simple test would be to open the browser or messages app or whatever app having an InputField, tap on the field and scan something... whatever get's scanned should be typed automatically in the InputField... this is a simple test, then you can try with the plugin.
Compare the EDA71 system settings with your CT50... make sure there are similar, or simply Restore to Defaults confs in your CT50

Regarding the GMS and non GMS I don't think it's related to the issue, for this you should check on the manufacturer info to see if they mention something related to the scanner and the GMS, but I doubt it.

The best way to know what's happening would be to debug the plugin running on the PDA 🤷‍♂️... 

These are my EDA51-1 System Settings

![IMAGE 2024-08-09 11:47:21](https://github.com/user-attachments/assets/5c9631cf-ee5c-4b73-8839-47408e73686c)
![IMAGE 2024-08-09 11:48:13](https://github.com/user-attachments/assets/00e5b38d-9c5c-49e1-a280-0c8707add193)
![IMAGE 2024-08-09 11:48:19](https://github.com/user-attachments/assets/dea97c19-4434-4545-8d80-5fd37b96b230)
![IMAGE 2024-08-09 11:48:28](https://github.com/user-attachments/assets/f6b094a2-b676-4032-856e-9c8dc495795f)
![IMAGE 2024-08-09 11:48:32](https://github.com/user-attachments/assets/11a08305-abfa-4515-821c-bd7c37fab1e8)
![IMAGE 2024-08-09 11:48:38](https://github.com/user-attachments/assets/52476172-e82d-4722-863a-dd807221ca1d)
![IMAGE 2024-08-09 11:48:48](https://github.com/user-attachments/assets/1c645585-ed83-46e1-a480-96e57d937e0f)
![IMAGE 2024-08-09 11:48:53](https://github.com/user-attachments/assets/478cbbbe-dc0c-4eae-abfa-70b1bbacfc4e)

**Comment by dandumit** [comment]
Thank you so much for continous support ! 
and please excuse me for wasting your time : let me explain : 

I was kind of clueless , I have went with device to an authorised Honeywll service center , technician reinstalled the SW / android.
Now seems to scan but android keypad does not work and I cannot progress further for moment. 

It seems that I am closer. For moment lesson learned it's that sw pack from oficial gateway it's not the best one....

Thank you,
Daniel

**Comment by dandumit** [comment]
Once again thank you for your time and apologies missleading.
I have upgraded this device CT50 from Android 4 to Android 6.0 but it seems that I have not completed all the steps . I am missingsome system services related to Honeywell sensor . I am still digging to find our what's missing and I will update case maybe some others may try this . 

Application works correclty now. 

Daniel

**Comment by luis901101** [comment]
Glad to help, I hope you get the solution soon 🤓.
“Application works well” you mean you can scan codes already?

**Comment by dandumit** [comment]
YEs , application works now !  
Unfortunately I still not know for sure how to completely upgrade the device . 

For any one following this path / upgrading some old devices please follow article :
[https://sps-support.honeywell.com/s/article/How-to-install-an-ECP-SCP-or-DCP-package-on-an-Android-device
](url)
statement  "Starting on Android 9 the Client Pack applications (SmartTE, BasicTE, Enterprise Browser and Honeywell Launcher) are now included in the Operating System." it's explanatory.

Thank you once again thank you Luis !
Daniel
