### ISSUE TITLE
UPC_E last digit not sending

### ISSUE THREAD

**Issue by Applecute** [luis901101/honeywell_scanner#25]
hi i have a problem regarding UPC_E last digit 

this is the sample of bar code [0123013]
![image](https://github.com/user-attachments/assets/ae29613c-1e76-4ee5-a166-1fa60dfe3595)

it not sending me last digit [7] to me is any setting i mistake?

i need 
![image](https://github.com/user-attachments/assets/0bba1195-ffd4-496b-b67f-c0e2420c00c1)
0123013[7] it return to me

**Comment by luis901101** [comment]
You have to set the required settings for it, check the honeywell sdk docs to know which property is, and check this issue https://github.com/luis901101/honeywell_scanner/issues/1 which is similar to your case
