### ISSUE TITLE
How to get scanned code type?

### ISSUE THREAD

**Issue by abdllhyvz** [luis901101/honeywell_scanner#6]
Hello, your package is working fine with scans but I couldn't figure out how to get scanned barcode type. I didn't see any method doing this. Is there a way that I can get barcode's type? Thank you.

**Comment by luis901101** [comment]
The scanned code type was not available until now with [v4.0.0+14](https://pub.dev/packages/honeywell_scanner/versions/4.0.0+14), note this is a breaking. Check the version's changelog and the readme migration instructions.

**Comment by abdllhyvz** [comment]
Thank you! That was a very nice update.

**Comment by luis901101** [comment]
> Thank you! That was a very nice update.

You’re welcome.
Check the breaking changes notes in changelog, there you will find how to get codeType.
Anyway when you migrate to the latest version you will find that the `ScannedData` object received in the `onDecoded` callback, has the scanned code and the code type as well as other properties…
