### ISSUE TITLE
Is there a way that I can control scanning sounds?

### ISSUE THREAD

**Issue by ayavuz-erbakir** [luis901101/honeywell_scanner#7]
I want to control scanning sounds like device is giving on success and error. Can I reach them or what is the way of it?

**Comment by luis901101** [comment]
You can control the scanning sounds by using properties. In the plugin's README.md there is a reference to a [BarcodeReader.html](https://github.com/luis901101/honeywell_scanner/blob/master/doc/BarcodeReader.html) and a [BarcodeReaderProperties.java](https://github.com/luis901101/honeywell_scanner/blob/master/doc/BarcodeReaderProperties.java) that describes each property allowed by honey well scanner. 
It's important to always read the documentation.
Anyway for this sound control you can use: `NTF_GOOD_READ_ENABLED` and `NTF_BAD_READ_ENABLED` both properties are bool.
Something like this:
```dart
Map<String, dynamic> properties = {
      'NTF_GOOD_READ_ENABLED': false,
      'NTF_BAD_READ_ENABLED': false,
    };
honeywellScanner.setProperties(properties);
```

**Comment by ayavuz-erbakir** [comment]
I was not meant to enable or disable them actually. I mean how can I make a scanning or error sound by myself in some situation.

**Comment by luis901101** [comment]
It was not clear enough in your first question. AFAIK the honeywell scanners doesnt allow to customize sounds by type of code, I mean you can’t configure to make the scanner emit an error beep when soecific type code is scanned.
The behavior you want is something beyond the scanner properties and configurations and therefore this plugin.
One thing you could do is to comfigure scanner to avoid scanning some types of codes, that way you dont have to deal with the error sound for some specific scanned codes.
Anyway what you want can be made easily by using a plugin for playing audio. 
You could do the following:
1. Disable `NTF_GOOD_READ_ENABLED` and `NTF_BAD_READ_ENABLED` properties.
2. Override `onDecoded(…)` and play custom sound according to you business logic by using a play audio plugin.
3. Also override `onError()` and play custom sound there too.

**Comment by ayavuz-erbakir** [comment]
@luis901101 Yes, it was my bad. As I see in java codes there is a method like `BarcodeReader.BAD_READ_NOTIFICATION `  which is giving error sound, so I wanted to ask if you have that method in package, too. If not, I will make it like you mentioned. Thanks.

**Comment by luis901101** [comment]
> @luis901101 Yes, it was my bad. As I see in java codes there is a method like `BarcodeReader.BAD_READ_NOTIFICATION ` which is giving error sound, so I wanted to ask if you have that method in package, too. If not, I will make it like you mentioned. Thanks.

Nope, currently there is no way to call scanner `notify(...)` function.  `BAD_READ_NOTIFICATION` and `GOOD_READ_NOTIFICATION` are just constants for the properties `badRead` and `goodRead` respectively, which are the ones that receive the `notify(...)` function, but currently it's not implemented a way to call this function from this plugin.
