### ISSUE TITLE
There is a newer version of the Honeywell Mobility SDK for Android available, v1.00.00.0143

### ISSUE THREAD

**Issue by mbalmer** [luis901101/honeywell_scanner#8]
Versopn 1.00.00.0143 adds a few more scanners, e.g. the CT45 and CT45XP.  Will you eventually update this module or is there an easy way to replace the DataCollection.aar file? I see that honeywell.aar and DataCollection.aar are identical.

**Comment by mbalmer** [comment]
The current modules implicates an minSdkVersion of 19.  Apparently the newer version ask for minSdkVersion 27?  That would break devices like the dolphin 75e (Android 6).

**Comment by luis901101** [comment]
Thanks for the notice. Yess there is an easy way you can use the new `DataCollection.aar` you just need to replace the one you were using, check the **Second** step in the readme, just make sure to use the same name that this plugin uses.
I will upgrade the plugin as well to use the new version but not soon.
I have not seen anything related to the new version yet, but what you mention about `minSdkVersion 27` is really a breaking change, I can't imagine what would this be a requirement, it's a huge jump in version, it would seem more like a mistake in the gradle definition.
Anyway I will check it when I have the time to upgrade the plugin.

**Comment by mbalmer** [comment]
I replaced honeywell.aar with the newer DataCollection.aar  and gave it a try (minSdkVersion still 19 ind the gradle file). That worked well.

**Comment by ebrahimmansur** [comment]
@mbalmer  hi, i was not able to download sdk like you did  , is there a way you can help me out

**Comment by luis901101** [comment]
@ebrahimmansur at the begining of this plugin’s readme it’s described where and how to download the mobility sdk which has the DataCollection.aar inside

**Comment by ebrahimmansur** [comment]
yes.... it seemed I needed to download the Honey well tool to access the zip file... thanks.

**Comment by novas1r1** [comment]
Is there any way to download this file from a mac? The Honeywell download manager doesn't work on my Mac T_T... Or is anyone able to send me the latest version of the file? That would really help!

**Comment by mbalmer** [comment]
> Is there any way to download this file from a mac? The Honeywell download manager doesn't work on my Mac T_T... Or is anyone able to send me the latest version of the file? That would really help!

Yes, it’s a nuisance that some companies in 2023 still think there is only Windows… FWIW, I use a Win 11 VM in VMWare Fusion.
